/* ============================================================================
 *  PROJECT     : Fuzzy Racers — AI Racing Game
 *  SUBJECT     : ISP568 Fuzzy Logic Systems
 *  FILE        : chatbot.js
 *  DESCRIPTION : "Fuzzy Logic Assistant" — an LLM-backed Q&A that replaces the
 *                old "How Fuzzy Logic Works" menu button. Launched from a
 *                themed icon in the bottom-right corner.
 *
 *                The assistant only accepts FOUR predefined questions (shown as
 *                quick-reply buttons — there is no free-text input):
 *                  • What is it?
 *                  • Why use it for racing AI?
 *                  • The 3-step pipeline
 *                  • What in this game is fuzzy?
 *
 *                Answers are generated by Google Gemini, grounded by a system
 *                prompt describing THIS game's engine. If the API key is blank
 *                or the request fails, it falls back to built-in canonical
 *                answers so the concept always shows (e.g. offline at a demo).
 *
 *                Self-contained: builds its own DOM and appends it to <body>.
 * ============================================================================
 */
(function () {
    'use strict';

    // ========================================================================
    //  CONFIG  —  PASTE YOUR GOOGLE GEMINI API KEY BELOW
    //  (Hardcoded on purpose: this build is for a live presentation demo.)
    //  Get a key at https://aistudio.google.com/apikey . Leave blank to run
    //  in offline mode (built-in answers, no network call).
    // ========================================================================
    const GEMINI_API_KEY = '';
    const GEMINI_MODEL   = 'gemini-2.0-flash';
    // ========================================================================

    const ENDPOINT = 'https://generativelanguage.googleapis.com/v1beta/models/'
        + GEMINI_MODEL + ':generateContent';

    // The ONLY inputs the assistant accepts (rendered as quick-reply buttons).
    const QUESTIONS = [
        'What is it?',
        'Why use it for racing AI?',
        'The 3-step pipeline',
        'What in this game is fuzzy?'
    ];

    // Canonical answers — used to (a) ground the LLM so it stays accurate and
    // (b) serve as the offline fallback if the API is unavailable. Plain text.
    const FALLBACK = {
        'What is it?':
            "Fuzzy logic reasons with degrees of truth instead of hard yes/no answers. "
          + "A fact like \"the player is close\" can be 0.7 true rather than simply true or "
          + "false, so many soft conditions blend together into one smooth decision.",
        'Why use it for racing AI?':
            "Race telemetry is continuous and messy — distance, speed, cornering, health, gap. "
          + "A traditional if/else AI either explodes with edge cases or jerks between behaviours "
          + "at hard thresholds. A fuzzy controller weighs every signal at once and produces a "
          + "smooth, defensible action — exactly what you want from a believable opponent.",
        'The 3-step pipeline':
            "1) Fuzzification — raw telemetry becomes degrees of membership in fuzzy sets like "
          + "very_close, fast, and critical.\n"
          + "2) Rule evaluation — 33 IF/THEN rules fire in parallel; each rule's strength is the "
          + "min() of its conditions (Mamdani AND), and outputs are aggregated by max().\n"
          + "3) Defuzzification — the aggregated curve is collapsed to one crisp number via the "
          + "centroid method, becoming the AI's throttle / brake / steering command.",
        'What in this game is fuzzy?':
            "• Speed control — throttle and brake from corner sharpness and distance.\n"
          + "• Powerup timing — when to fire, from gap, health, and \"powerup ready\" together.\n"
          + "• Aggression — a defensive-vs-attacking blend of gap, health and proximity.\n"
          + "• Braking under risk — at critical health the AI brakes earlier and softens.\n"
          + "Press F during a race to watch the engine think live."
    };

    const SYSTEM_PROMPT =
        "You are the \"Fuzzy Logic Assistant\" inside Fuzzy Racers, a browser racing game whose "
      + "AI opponents are driven by a Mamdani-style fuzzy inference engine, built for the ISP568 "
      + "Fuzzy Logic Systems course.\n\n"
      + "Engine facts you must stay consistent with:\n"
      + "- 6 crisp inputs: distance, player_speed, corner, health, gap, powerup.\n"
      + "- 5 outputs: throttle, brake, steering, aggression, use_powerup.\n"
      + "- 33 IF/THEN rules. AND = min(), rule aggregation = max() (Zadeh operators).\n"
      + "- Defuzzification = centroid over 101 samples.\n"
      + "- maxHealth = armor x 15; cars explode at 0 HP.\n\n"
      + "Answer ONLY the user's selected question. Be concise and presentation-ready "
      + "(2-4 short sentences, or a tight list when natural), friendly, and accurate. "
      + "Plain text only — no markdown headers, bold, or asterisks. Stay strictly on the topic "
      + "of fuzzy logic in this game.";

    // ------------------------------------------------------------------------
    // DOM build
    // ------------------------------------------------------------------------
    let panel, messagesEl, chipsEl, fab, busy = false;

    function build() {
        // Launcher (bottom-right), themed to match the old menu button.
        fab = document.createElement('button');
        fab.className = 'fla-fab';
        fab.type = 'button';
        fab.setAttribute('aria-label', 'How Fuzzy Logic Works');
        fab.innerHTML = '<span class="fla-fab-icon">🧠</span>'
                      + '<span class="fla-fab-label">How Fuzzy Logic Works</span>';
        document.body.appendChild(fab);

        // Chat panel.
        panel = document.createElement('div');
        panel.className = 'fla-panel';
        panel.setAttribute('role', 'dialog');
        panel.setAttribute('aria-label', 'Fuzzy Logic Assistant');
        panel.innerHTML =
            '<div class="fla-header">'
          +   '<span class="fla-title"><span class="fla-title-icon">🧠</span> Fuzzy Logic Assistant</span>'
          +   '<button class="fla-close" type="button" aria-label="Close">✕</button>'
          + '</div>'
          + '<div class="fla-messages" id="flaMessages"></div>'
          + '<div class="fla-chips" id="flaChips"></div>'
          + '<div class="fla-foot">Pick a question — answers are generated live by an LLM.</div>';
        document.body.appendChild(panel);

        messagesEl = panel.querySelector('#flaMessages');
        chipsEl    = panel.querySelector('#flaChips');

        // Quick-reply chips (the only accepted inputs).
        for (const q of QUESTIONS) {
            const chip = document.createElement('button');
            chip.className = 'fla-chip';
            chip.type = 'button';
            chip.textContent = q;
            chip.addEventListener('click', () => ask(q));
            chipsEl.appendChild(chip);
        }

        // Greeting.
        addMessage('bot',
            "Hi! I can explain the fuzzy logic powering this game's AI. Tap a question below.");

        // Events.
        fab.addEventListener('click', toggle);
        panel.querySelector('.fla-close').addEventListener('click', close);
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && panel.classList.contains('open')) close();
        });
    }

    function toggle() { panel.classList.contains('open') ? close() : open(); }
    function open()   { panel.classList.add('open'); fab.classList.add('active'); }
    function close()  { panel.classList.remove('open'); fab.classList.remove('active'); }

    // ------------------------------------------------------------------------
    // Messages
    // ------------------------------------------------------------------------
    function addMessage(who, text, opts) {
        opts = opts || {};
        const row = document.createElement('div');
        row.className = 'fla-msg fla-msg-' + who;
        const bubble = document.createElement('div');
        bubble.className = 'fla-bubble';
        bubble.textContent = text;                  // textContent → no HTML injection
        row.appendChild(bubble);
        if (opts.note) {
            const note = document.createElement('div');
            note.className = 'fla-note';
            note.textContent = opts.note;
            row.appendChild(note);
        }
        messagesEl.appendChild(row);
        messagesEl.scrollTop = messagesEl.scrollHeight;
        return bubble;
    }

    function showTyping() {
        const row = document.createElement('div');
        row.className = 'fla-msg fla-msg-bot fla-typing';
        row.innerHTML = '<div class="fla-bubble"><span></span><span></span><span></span></div>';
        messagesEl.appendChild(row);
        messagesEl.scrollTop = messagesEl.scrollHeight;
        return row;
    }

    function setBusy(state) {
        busy = state;
        chipsEl.querySelectorAll('.fla-chip').forEach(c => { c.disabled = state; });
    }

    // ------------------------------------------------------------------------
    // Ask flow
    // ------------------------------------------------------------------------
    async function ask(question) {
        if (busy) return;
        addMessage('user', question);
        setBusy(true);
        const typing = showTyping();

        try {
            const answer = await callGemini(question);
            typing.remove();
            addMessage('bot', answer);
        } catch (err) {
            typing.remove();
            // Graceful fallback so the concept always shows.
            addMessage('bot', FALLBACK[question], {
                note: GEMINI_API_KEY
                    ? 'Offline answer (LLM request failed)'
                    : 'Offline answer (no API key set in chatbot.js)'
            });
        } finally {
            setBusy(false);
        }
    }

    async function callGemini(question) {
        if (!GEMINI_API_KEY) throw new Error('no-key');

        const body = {
            system_instruction: { parts: [{ text: SYSTEM_PROMPT }] },
            contents: [{
                role: 'user',
                parts: [{
                    text: 'Question: ' + question
                         + '\n\nReference answer to stay consistent with:\n' + FALLBACK[question]
                }]
            }],
            generationConfig: { temperature: 0.4, maxOutputTokens: 400 }
        };

        const resp = await fetch(ENDPOINT + '?key=' + encodeURIComponent(GEMINI_API_KEY), {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body)
        });
        if (!resp.ok) throw new Error('http-' + resp.status);

        const data = await resp.json();
        const text = data
            && data.candidates && data.candidates[0]
            && data.candidates[0].content && data.candidates[0].content.parts
            && data.candidates[0].content.parts.map(p => p.text || '').join('').trim();
        if (!text) throw new Error('empty');
        return text;
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', build);
    } else {
        build();
    }
})();
